/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import Model.AdminDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import Model.ConexionDB;
import java.sql.Connection;
import java.sql.SQLException;
/**
 *
 * @author Sebastian JB
 */
public class Add extends javax.swing.JPanel {

    /**
     * Creates new form Add
     */
    public Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Origin = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        destino = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        fechaida = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        fechregreso = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        numeroasientos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        horaida = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horallegada = new javax.swing.JTextField();
        btnagregarvielo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel13.setText("Add Flights");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 190, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Origin");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 50, -1));

        Origin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bogota", "Cartagena", "Medellin", " " }));
        Origin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Origin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriginActionPerformed(evt);
            }
        });
        add(Origin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Destination");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bogota", "Cartagena", "Medellin" }));
        destino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 120, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Entry date");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        add(fechaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText(" Departure date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, 20));

        fechregreso.setMinSelectableDate(new java.util.Date(-62135747891000L));
        fechregreso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechregresoPropertyChange(evt);
            }
        });
        add(fechregreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 120, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Seats available");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, 20));

        numeroasientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31  ", "32  ", "33  ", "34  ", "35  ", "36  ", "37  ", "38  ", "39  ", "40  ", "41  ", "42  ", "43  ", "44  ", "45  ", "46  ", "47  ", "48  ", "49  ", "50  ", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        numeroasientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(numeroasientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, -1));

        jLabel8.setText("hora ida. format  00:00:00");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));
        add(horaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 30));

        jLabel7.setText("hora llegada. format 00:00:00");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, 30));
        add(horallegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, 30));

        btnagregarvielo.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnagregarvielo.setText("Add");
        btnagregarvielo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagregarvielo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarvieloMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnagregarvieloMousePressed(evt);
            }
        });
        btnagregarvielo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarvieloActionPerformed(evt);
            }
        });
        add(btnagregarvielo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void OriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OriginActionPerformed

    private void fechregresoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechregresoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fechregresoPropertyChange

    private void btnagregarvieloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarvieloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarvieloMouseClicked

    private void btnagregarvieloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarvieloMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarvieloMousePressed

    private void btnagregarvieloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarvieloActionPerformed
        String Org = (String) Origin.getSelectedItem();
        String Dstino = (String) destino.getSelectedItem();
        java.util.Date fechadIda = fechaida.getDate();
        java.util.Date fechaVuelta = fechregreso.getDate();
        String asientos = (String) numeroasientos.getSelectedItem();

        if (asientos != null && !asientos.trim().isEmpty()) {
            try {
                int asientosInt = Integer.parseInt(asientos.trim()); // Elimina los espacios antes de convertir
                // Ahora puedes usar asientosInt en tu consulta
            }catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El número de asientos no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione el número de asientos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        String h_ida = horaida.getText();
        String h_llegada = horallegada.getText();

        if (Org.equals("-------") || Dstino.equals("-------") || fechadIda == null || fechaVuelta == null || asientos.equals(" ")) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione todos los campos requeridos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else {
            // Convertir las fechas de java.util.Date a java.sql.Date
            java.sql.Date sqlFechaIda = new java.sql.Date(fechadIda.getTime());
            java.sql.Date sqlFechaVuelta = new java.sql.Date(fechaVuelta.getTime());

            // Obtener la conexión a la base de datos
            try (Connection connection = ConexionDB.conectar()) {
                // Crear una instancia de AdminDAO con la conexión
                AdminDAO adminDAO = new AdminDAO(connection);

                // Llamar al método para agregar el vuelo
                boolean vueloAgregado = adminDAO.agregarVuelo(Org, Dstino, sqlFechaIda, sqlFechaVuelta, Integer.parseInt(asientos), h_ida, h_llegada);

                // Verificar si el vuelo fue agregado exitosamente
                if (vueloAgregado) {
                    JOptionPane.showMessageDialog(this, "Vuelo agregado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al agregar el vuelo", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error de conexión: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnagregarvieloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Origin;
    private javax.swing.JButton btnagregarvielo;
    private javax.swing.JComboBox<String> destino;
    private com.toedter.calendar.JDateChooser fechaida;
    private com.toedter.calendar.JDateChooser fechregreso;
    private javax.swing.JTextField horaida;
    private javax.swing.JTextField horallegada;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> numeroasientos;
    // End of variables declaration//GEN-END:variables
}
