/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Model.Sesion;
import Model.Usuario;
import Model.UsuarioDAO;
import Model.SesionDatosVuelo;
import javax.swing.*;
/**
 *
 * @author valer
 */
public class sistemadepago extends javax.swing.JFrame {
     
    /**
     * Creates new form Registro
     */
    public sistemadepago() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        cargarDatosUsuario();
        cargarDatosVuelo(); 
        
        
        
    }
    
     private void cargarDatosVuelo() {
        // Recuperamos los datos de la clase SesionDatosVuelo usando los getters
        String origen = SesionDatosVuelo.getOrigen();
        String destino = SesionDatosVuelo.getDestino();
        String fechaIda = SesionDatosVuelo.getFechaIda();
        String fechaVuelta = SesionDatosVuelo.getFechaVuelta();
        int numeroPersonas = SesionDatosVuelo.getAsientosDisponibles();
        int idVuelo = SesionDatosVuelo.getIdVuelo();
       

        // Asignamos esos valores a los campos de texto (JTextField) en el JFrame
        vorigen.setText(origen);      // Asigna el valor de origen al JTextField correspondiente
        vdestino.setText(destino);    // Asigna el valor de destino
        fechaida.setText(fechaIda); // Asigna el valor de la fecha de ida
        fechavuelta.setText(fechaVuelta); // Asigna el valor de la fecha de vuelta
        numerodeasientos.setText(String.valueOf(numeroPersonas)); // Asigna el valor del número de personas
        id.setText(String.valueOf(idVuelo));
       
    }


    private void cargarDatosUsuario() {
        int idUsuario = Sesion.getIdUsuario(); // Obtener el id_usuario desde la sesión

        // Obtener el usuario de la base de datos usando el id_usuario
        UsuarioDAO userDao = new UsuarioDAO();
        Usuario usuario = userDao.obtenerUsuarioPorId(idUsuario);

        if (usuario != null) {
            txtnombre.setText(usuario.getNombre());
            txtcorreo.setText(usuario.getCorreo());
            txtconfcorreo.setText(usuario.getCorreo());
            txttel.setText(usuario.getTelefono());
            txtid.setText(usuario.getIdentificacion());
            

          
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron los datos del usuario.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        selectid = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        vdestino = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtconfcorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fechavuelta = new javax.swing.JTextField();
        fecha_ida = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        vorigen = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        preciovuelo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fechaida = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        horasalida = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        horallegada = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        numerodeasientos = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Datos de contacto");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 300, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Celular *");
        jLabel2.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 70, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "Men", "Woman" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(64, 22));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 140, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Nombre *");
        jLabel7.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Fecha de nacimiento *");
        jLabel13.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Sexo *");
        jLabel14.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 70, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Correo *");
        jLabel15.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 70, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Confirmar correo *");
        jLabel16.setPreferredSize(new java.awt.Dimension(58, 20));
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tipo de identificación *");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Numero de identificación *");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));
        jPanel2.add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 160, 30));

        selectid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Pasaporte de extrangeria" }));
        jPanel2.add(selectid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 160, 30));

        jPanel4.setBackground(new java.awt.Color(38, 75, 100));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(192, 201, 211)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NOESAVIANCA");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 20));

        jButton2.setText(" ⭠");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -10, 70, 60));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Datos de vuelo");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 220, -1));

        jButton1.setBackground(new java.awt.Color(38, 75, 100));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar y pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 160, 40));

        vdestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vdestinoActionPerformed(evt);
            }
        });
        jPanel2.add(vdestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 110, 30));

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 160, 30));
        jPanel2.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 160, 30));

        txtconfcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfcorreoActionPerformed(evt);
            }
        });
        jPanel2.add(txtconfcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 160, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Datos personales");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 220, -1));

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 160, 30));

        jLabel1.setText("Fecha vuelta");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        jLabel6.setText("Destino");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));
        jPanel2.add(fechavuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 110, 30));

        fecha_ida.setMinSelectableDate(new java.util.Date(-62135747891000L));
        fecha_ida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fecha_idaPropertyChange(evt);
            }
        });
        jPanel2.add(fecha_ida, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 160, 30));

        jLabel12.setText("Origen");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));
        jPanel2.add(vorigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 100, 30));

        jLabel17.setText("ID vuelo");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, -1, -1));

        preciovuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciovueloActionPerformed(evt);
            }
        });
        jPanel2.add(preciovuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 100, 30));

        jLabel18.setText("Fecha ida");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));
        jPanel2.add(fechaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 100, 30));

        jLabel19.setText("Hora salida");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));
        jPanel2.add(horasalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 100, 30));

        jLabel20.setText("Hora llegada");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));
        jPanel2.add(horallegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 110, 30));

        jLabel21.setText("Asientos");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        numerodeasientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numerodeasientosActionPerformed(evt);
            }
        });
        jPanel2.add(numerodeasientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 40, 30));

        jLabel22.setText("Precio de vuelo");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 60, 30));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new planes().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String Nombre =  txtnombre.getText();
       String celular = (String) txttel.getText();
       String correo = txtcorreo.getText();
       String confCorreo = txtconfcorreo.getText();
       String identificacion = txtid.getText();
       String id = (String) selectid.getSelectedItem();
       
       if (Nombre.isEmpty() || identificacion.isEmpty() || correo.isEmpty() || celular.isEmpty() || id == null) {
    JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos requeridos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return; 
}
if (!correo.equals(confCorreo)) {
    JOptionPane.showMessageDialog(this, "Por favor, confirme su dirección de correo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return; 
}

String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
if (!correo.matches(emailRegex)) {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese un correo electrónico válido.", "Advertencia", JOptionPane.WARNING_MESSAGE);
          
} // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtconfcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfcorreoActionPerformed

    private void fecha_idaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fecha_idaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_idaPropertyChange

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void preciovueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciovueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preciovueloActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void numerodeasientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerodeasientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numerodeasientosActionPerformed

    private void vdestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vdestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vdestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemadepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemadepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemadepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemadepago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistemadepago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fecha_ida;
    private javax.swing.JTextField fechaida;
    private javax.swing.JTextField fechavuelta;
    private javax.swing.JTextField horallegada;
    private javax.swing.JTextField horasalida;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField numerodeasientos;
    private javax.swing.JTextField preciovuelo;
    private javax.swing.JComboBox<String> selectid;
    private javax.swing.JTextField txtconfcorreo;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField vdestino;
    private javax.swing.JTextField vorigen;
    // End of variables declaration//GEN-END:variables
}
